services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 61972:1972
      - 62773:52773
      - 63773:53773
    volumes:
      - ./:/home/irisowner/dev
    environment:
      - FHIR_INSIGHT_LLM_MODEL=${FHIR_INSIGHT_LLM_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_ENGINE=$AI_ENGINE
      - API_KEY=$API_KEY
      - LLM_MODEL_NAME=$LLM_MODEL_NAME
      - AZURE_ENDPOINT=$AZURE_ENDPOINT
      - API_VERSION=$API_VERSION
