services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 61972:1972
      - 62773:52773
      - 63773:53773
    volumes:
      - ./:/home/irisowner/dev
    environment:
      - FHIR_INSIGHT_LLM_MODEL=${FHIR_INSIGHT_LLM_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - default
    
  streamlit:
    container_name: fhirinsight-frontend-1
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - 8501:8501
    volumes:
      - ./python/:/app/
    networks:
      - default

networks:
  default:
    driver: bridge